guests = ['Jim','Danny','Kevin']
print("I invited " + guests[0] + " for dinner")
print("I invited " + guests[1] + " for dinner")
print("I invited " + guests[2] + " for dinner")
print("But " + guests[1] + " won't be able to come")
#Substitui Danny por Patrick na lista
guests [1] = 'Patrick'
print("So I invited " + guests[1] + " for dinner")
print("I'm getting a bigger dinner table, so I can invite more people")
guests.insert(0, 'Harry')
guests.insert(2, 'Will')
guests.append('Tom')
print(guests)
print('I invited ' + guests[0])
print('I invited ' + guests[1])
print('I invited ' + guests[2])
print('I invited ' + guests[3])
print('I invited ' + guests[4])
print('I invited ' + guests[5])
print("Bad news, the table won't arrive on time")
print("And I already sold my old one")
print("Best I can do is have two of you for dinner")
not_guest = guests.pop()
print('Sorry ' + not_guest + ", I can't invite you")
not_guest = guests.pop(3)
print('Sorry ' + not_guest + ", I can't invite you")
not_guest = guests.pop(2)
print('Sorry ' + not_guest + ", I can't invite you")
not_guest = guests.pop(0)
print('Sorry ' + not_guest + ", I can't invite you")
print(guests[0]+ ", you're still invited for dinner")
print(guests[1]+ ", you're still invited for dinner")
guests.clear
print (guests)